name: Continous integration

# Sets environment variables for all jobs
env:
  PYTHONPATH: :/home/runner/work/smarte/smarte:/home/runner/work/smarte/smarte/analyzeSBML:/home/runner/work/smarte/smarte/fitterpp

on: [push]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: install submodules
      run: git submodule update --init --recursive
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pwd;
        echo "$PYTHONPATH";
        nosetests tests
