name: Continous integration

# Sets environment variables for all jobs
# Makes the dependent repositories submodules
env:
  PYTHONPATH: :/home/runner/work/smarte/smarte:/home/runner/work/smarte/smarte/SBMLModel:/home/runner/work/smarte/smarte/fitterpp

on: [push]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: install SBMLModel
      run: git submodule add https://github.com/ModelEngineering/SBMLModel.git
    - name: install fitterpp
      run: git submodule add https://github.com/ModelEngineering/fitterpp.git
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pwd;
        echo "$PYTHONPATH";
        nosetests tests
